### PR TITLE
Frontend fix for search - closes #52

### LINKED ISSUE #52: Search not returning any results on searchbar

### PR DESCRIPTION
**Pull request by andela-oakinniranye**

### CODE REVIEW

**Comment by andela-iamadi** [comment]
http://zhishitest-pr-71.herokuapp.com/search?q=kbl breaks

What's up with that?

File: app/js/utils/webAPI.js [hunk 1]
```diff
@@ -3,9 +3,11 @@ import Auth from '../auth';
 import fetch from 'isomorphic-fetch';
 import isEmpty from './isEmpty';
 
+import $ from 'jquery';
+
 const requestPath = (path, method, data = {}) => {
   if (method === 'GET' && !isEmpty(data)) {
-    return path + '?' + encodeURIComponent(JSON.stringify(data));
+    return path + '?' + $.param(data);
```
Comment (andela-iamadi) [inline app/js/utils/webAPI.js]: We're pushing back on the use of `jquery` so as to work towards removing it completely. It's a really heavy library if its purpose in this file would be limited to encoding param

**Comment by andela-bebowe** [comment]
@andela-oakinniranye @andela-iamadi I can't access the deployment for this PR, Heroku no such app issue
